devkitPro/libogc

- gc/ogc/system.h
- libogc/system.c
Useful for GC/Wii specific tasks, e.g: Gamecube saves, playrecord
> Add SYS_Time which returns ticks since 2000

- libogc/system.c
gettime is improper and I failed to notice this as I had some test code in my local branch, after resetting and pull master the issue became apparent, this fixes that issue.
> Fix SYS_Time, use __SYS_GetRTC rather than gettime

- libogc/card.c
Turns out that same filenames for the same game with differing cases can exist.
https://github.com/suloku/gcmm/issues/24
> Case sensitivity

- gc/network.h
- libogc/network_wii.c
- lwip/network.c
This is required to have dhcp work with dolphin, as the slower network code will ALWAYS have dhcp timeout before the ip is bound.
The fix on dolphin is being worked on, but a variable timeout cant hurt either way.
> if_config now requires and allows for a variable amount of dhcp retries.

- gc/ogc/card.h
If not, then CARD_Create() mysteriously returns CARD_ERROR_FATAL_ERROR.
> documentation: memcard file size clarification

- libogc/timesupp.c
tp->tv_nsec and tp->tv_usec should define the number of nanosecs and microsecs elapsed and their value should not be more than 1 second.
In lwp_watchdog.h tick_microsecs is defined as 
#define tick_microsecs(ticks) ((((u64)(ticks)*8)%(u64)(TB_TIMER_CLOCK/125)))
TB_TIMER_CLOCK/125 is 486. It means that the gives the rest of 486 which is wrong.
The correct function is "ticks_to_microsecs".
Anyhow also with these fixes gettimeoftheday() and clock_gettime() are not fully correct.
The result of tv_sec is correct for both, reppresenting the number of seconds since 00:00 hours, Jan 1, 1970 UTC.
tv_nsec in clock_gettime and tv_usec in __libogc_gettod_r should be respectively the number of nanoseconds and microseconds expired in the current second but instead they are values taken from the …
> Fix for clock_gettime and gettimeoftheday

- wiiuse/classic.c
The Wii U Pro controller does not provide calibration data therefore these data have been written in the code (classic.c).
However the min and max values (0 and 0xFF) are not correct and far from the real values.
More convenient values should be min=48 and max=208.
These values come from testing 2 Wii U Pro controller
Wrong calibration data lead to wrong polar coordinates values (in particular exp.classic.ljs.mag).
> Fixed Wii U PRO controller min and max calibration

- gc/network.h
- lwip/network.c
Originally from: https://github.com/ExtremsCorner/libogc-rice/commit/0aeb9c9ae13d296e63daf18381837825d0916426
> - Add net_gethostip and net_get_mac_address for GameCube

- gc/aesndlib.h
- gc/asndlib.h
- libaesnd/aesndlib.c
- libasnd/asndlib.c
Fairly trivial correctness stuff that squashes more missing prototype warnings.
> asndlib/aesndlib: Amend prototypes for functions with no arguments

- gc/network.h
The definition already has a void in it, this just amends the prototype to match.
> gc/network: Add missing void in empty parameter list for net_init()

- gc/bte/bte.h
- lwbt/bte.c
- lwbt/btmemr.c
- lwbt/btmemr.h
- lwbt/btpbuf.c
- lwbt/btpbuf.h
- lwbt/hci.c
- lwbt/hci.h
- lwbt/l2cap.c
- lwbt/l2cap.h
- lwbt/physbusif.c
- lwbt/physbusif.h
More clean-up and warnings resolved, just in a different lib. After this, #24, and #26 essentially all of the exposed public interface has their prototypes amended except for one function outside of lwbt, which will be fixed in its own PR.
> lwbt: Amend prototypes that take no arguments

- gc/di/di.h
- libdi/di.c
This also allows getting rid of casts that would otherwise hide bugs if the `DISC_INTERFACE` functions ever change in the future (unlikely, but still always nice to allow the compiler to point out any issues if it does).
> libdi: Amend prototypes for functions with no arguments

- gc/ogc/system.h
- libogc/exception.c
- libogc/system.c
`__exception_sethandler()` expects handler functions taking a `frame_context*`, and `IRQ_Request` expects functions taking a `u32` signifying an IRQ and a `void*` for passing along any extra contextual data.
> Amend prototypes for exception handlers and interrupt handlers/callbacks

- libogc/dvd.c
These aren't used anywhere else in the library and aren't exposed in the public headers (aside from two of them, which are explained below) so make these internally linked and hidden. Even the callback typedefs in several of the functions' parameter lists aren't exposed in the header either.
DVD_ReadAbsAsyncPrio() and DVD_ReadDiskID() are already exposed in headers, so their prototypes don't need to be present here and can be removed. The dvd.h header which is included already can provide these prototypes.
> libogc/dvd: Make functions internally linked where applicable

- libogc/dvd.c
Missed these when making the other ones static in 4507735980f13b82d762fc5046c8f93aa0faa73b, my bad.
> dvd: Make four other functions internally linked

- libogc/wiisd.c
These aren't exposed in any public headers and are only used to form part of the __io_wiisd DISC_INTERFACE instance. Also removes unnecessary function pointer casts that are no longer necessary.
> libogc/wiisd: Make functions internally linked where applicable

- gc/sdcard/card_io.h
- libogc/sdgecko_io.c
These functions are used nowhere internally, so these were likely intended to be callable from user code.
Also renames the defines intended to be used with sdgecko_getAddressingType() to make them more indicative of what they're used for so they aren't ambiguous in the context of user code. Also convert them to an enum so they can be symbolic constants during debugging instead of a magic number (and be more type safe in certain scenarios)
> libogc/card_io: Expose missing function prototypes in public header

- libdb/debug.c
- libdb/debug_supp.c
- libdb/debug_supp.h
- libdb/tcpip.c
- libdb/tcpip.h
- libdb/uIP/bba.c
- libdb/uIP/memr.c
- libdb/uIP/memr.h
- libdb/uIP/uip_arch.h
- libdb/uIP/uip_ip.c
- libdb/uIP/uip_ip.h
- libdb/uIP/uip_netif.c
- libdb/uIP/uip_netif.h
- libdb/uIP/uip_pbuf.c
- libdb/uIP/uip_pbuf.h
- libdb/uIP/uip_tcp.c
- libdb/uIP/uip_tcp.h
Silences a bunch more of -Wmissing-prototypes warnings. Note that this also corrects the prototype of dbg_exceptionhandler in debug.c to take a frame_context*, as it's required for the interface that uses it.
> libdb: Add missing void in empty function parameter lists

- libogc/card.c
This is only used within this translation unit and nowhere else.
> libogc/card: Make __card_findnext() internally linked

- gc/ogc/gx.h
These were likely intended to be exposed but were forgotten or missed.
I was able to glean enough info off GX_LoadNrmMtxImm() to put a docstring in for GX_LoadNrmMtxImm3x3(), but I don't particularly know what the one for GX_SetTexCoordCylWrap() should be.
> libogc/gx: Expose missing prototypes in public header

- libogc/texconv.c
Makes MakeTexture565's prototype visible in the .c file, getting rid of a -Wmissing-prototypes warning
> libogc/texconv: Add missing include in .c file

- lwbt/bte.c
- lwbt/hci.c
These aren't used anywhere except within their respective translation units. Silences more -Wmissing-prototypes warnings.
> lwbt/hci: Mark hci_get_link(), hci_cmd_ass(), and bte_hci_initcore_complete2() as internally linked

- gc/mp3player.h
- libmad/mp3player.c
This also corrects the function prototype of DataTransferCallback() which should have been specified with an s32 parameter representing a voice, rather than an empty parameter.
> mp3player: Amend function prototypes

- gc/ogc/dsp.h
This was missing a prototype, and given this isn't used internally, it was likely meant to be used from user code to query state.
> libogc/dsp: Expose DSP_GetDMAStatus() in the public header

- wiiuse/motion_plus.c
Allows the compiler to see exported functions, eliminating some -Wmissing-prototypes warnings.
> wiiuse/motion_plus: Include motion_plus.h

- gc/ogc/usbstorage.h
This is intended to be callable from user code (otherwise, it obviously can never be disabled). This also resolves a -Wmissing-prototype warning.
> libogc/usbstorage: Expose USBStorage_Deinitialize() in the public header

- libogc/dvd.c
- libogc/gcsd.c
- libogc/usbstorage.c
This prevents warnings about incompatible function pointer types from being silenced (which actually turned out to be the case in gcsd). This also adjusts the prototypes to use `sec_t` instead of `u32` where applicable, as the `DISC_INTERFACE` struct uses `sec_t` for the parameters. Given that `sec_t` is currently defined as a typedef to `uint32_t` this has no behavioral change.
> general: Remove casts in DISC_INTERFACE initializers

- gc/ogc/system.h
This is likely intended to be exposed to user code. Without it, there would be no way to reset performance counter registers, only start and stop them.
This also silences a -Wmissing-prototypes warning.
> libogc/system: Expose SYS_ResetPMC() in the public header

- libogc/gu.c
The previous code is considered an old form of declaration and will cause -Wold-style-declaration warnings.
> libogc/gu: Place register keyword before other keywords in declarations

- libogc/system.c
This is only ever memcpy'd and not modified, so allow the compiler toss it into the read-only segment
> libogc/system: Make dsp_initcode const

- libogc/gx.c
Untested (I only found this bug by looking at disassembly), but @stenzek independently found out the value returned by the left-shifting version of GX_ReadClksPerVtx() had to be shifted right by 16 to be realistic.
> gx: fix GX_ReadClksPerVtx() shift

- libogc/dvd.c
The previous specifier being used was for an unsigned int, however a pointer variable was being passed instead. Based off the incorrect name of the function in the format string, this was a copy-paste error
> libogc/dvd: Correct printf specifier in DVD_LowGetStatus()

- libogc/dvd.c
These are only ever read from and not modified.
> libogc/dvd: Mark file-scope arrays as const where applicable

- gc/network.h
Cf. https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Core/IOS/Network/IP/Top.cpp#L608-L609
These `#define`s don't affect lwip/GC networking at all. The `POLLIN` mask is defined per POSIX:
> [The POLLIN] flag shall be equivalent to POLLRDNORM | POLLRDBAND.
> Fix POLL* definitions per Dolphin

- gc/ogc/si.h
- libogc/si.c
This fixes use of the polling interrupt, fixes controller type queries, and adds controller type decoding.
Keyboard decoding is known to not be quite right.
> SI fixes and additions

- gc/ogc/system.h
- libogc/system.c
The intent behind this is to prevent reuse of padding for other applications, and clear invalid settings as done by later versions of the Dolphin SDK and all versions of the Revolution SDK.
The check has been somewhat enhanced from the Dolphin/Revolution SDK, but does not still include checking of the parity bit. That's down to the Game Boy Player Start-Up Disc and Game Boy Interface.
> Support Game Boy Player Start-Up Disc settings

- gc/ogc/semaphore.h
- libogc/semaphore.c
while discovering semaphore's i noticed the code apparently doesn't have the [GetValue](https://www.man7.org/linux/man-pages/man3/sem_getvalue.3.html) function , which returns the semaphore value. 
it can be used to check on the state of the semaphore (in my testing i used it to see if a SemPost was left unhandled when shutting down, which could signal its still busy)
> introduce LWP_SemGetValue

- gc/lwip/lwipopts.h
- lwip/arch/gc/netif/gcif.c
- lwip/core/ipv4/ip.c
- lwip/network.c
This is necessary to make TCP usable with 100BASE-TX due to the BBA's 2 KiB receive buffer constantly suffering from buffer overruns due to the 27 Mbps EXI bottleneck.
> lwIP fixes

- gc/mad.h
- gc/ogc/cast.h
- gc/ogc/machine/processor.h
Not sure why I'm only hitting this now, but there are some combinations of flags (I think `-std=c99` is enough, but I'm not 100% sure) whereby `asm`/`asm volatile` isn't defined and you need `__asm__`/`__asm__ __volatile__`. When it is defined, this patch is a no-op. When it's not, this fixes the build.
> Use __asm__ instead of asm since asm isn't always defined

- gc/ogc/usb.h
- libogc/usb.c
while I was working on my HID controller code I needed these functions to get the device's report descriptor (which describes what is in the report data and which bits describe what)
i had to split this up sadly as the report descriptor has no static size or layout... -_-
> implement retrieving the USB reportDescriptor & it's size

- gc/ogc/machine/processor.h
- libogc/arqmgr.c
This PR adds "memory" clobbers to the ISR disable/restore/enable/flash operations, which were sorely needed but missing. Inspired by the debugging work on #103, though it won't necessarily fix that (it may or may not, and we may want to make other changes too) it's something that needs to be done regardless since interrupts can fire as a result of these and regions protected by disabling interrupts should be treated as critical sections.
While I was there I also made the style at least consistent.
> ogc: Cleanup and add memory clobbers to ISR operations

- gc/ogc/es.h
just a minor change to remove a filler byte and name it properly.
edit : https://wiibrew.org/wiki/Title_metadata#Header
> tmd's 0x183 byte is for marking it as a vwii title

- gc/lwip/memp.h
- lwip/core/memp.c
- lwip/core/pbuf.c
This cherry-picks some upstream code that redoes how pbuf "pool" allocation works, which (in my testing) resolves the issue @bendmorris was having in #103 without having to invasively insert interrupt disabling/enabling code. I'd appreciate it if this could get more testing before merging, however, since my own testing was pretty limited.
> lwIP: Refresh pbuf code with cherry-picked upstream

- gc/ogc/card.h
- gc/ogc/es.h
- libogc/card.c
These are changes i found in GCMM that i merged back into libogc.
what this changes : 
* fixes a bug #113 ( thx suloku )
* small es.h/tmd typo
* expose get & set statusex through new functions
* introduce CARD_GetSerialNo & CARD_GetFreeBlocks
* make the internal read/write/erasesector functions not static so tools like GCMM can use them without needing a copy of card.c
i have a working GCMM fork that works with these changes, which i will upstream once this is merged.
so if there are any comments i can change it in GCMM at the same time :)
> card fixes and adjustments

- libogc/card.c
https://github.com/devkitPro/libogc/issues/120
> Correctly calculte address for 0x800000 onwards in ogc_card_writepage()

- gc/ogc/lwp_watchdog.h
Trying to use this macro caused a compiler error (unless I left out a parenthesis from my code).
> lwp_watchdog.h: remove unmatched parenthesis from tick_nanosecs()

- gc/ogc/es.h
it is better to leave it alone untill we know exactly what the field is anyway
> revert es.h renamed property to fix build on some applications

- libogc/system.c
also unmask the irq after callback so pressing it again re-triggers the irq
Things to note : 
* the registry always contains the state of the reset button ( 0 = pressed, 1 = unpressed ) and the IRQ only triggers when going from 1 to 0 (it doesn't trigger when holding it, or releasing it)
* the while loop i left as is, besides it now checking on reset not being pressed (to deal with debounce)
* callback is executed when the button is pressed (unlike before where it only executed if it wasn't pressed)
* IRQ is unmasked after the callback so the IRQ can be triggered again ( and therefor acts the same on GC and Wii )
> system: check reset button state correctly on gamecube

- gc/wiiuse/wiiuse.h
Fix `nunchul button codes` when it was supposed to be `nunchuk button codes`
> Fix a typo

- lwip/network.c
Currently if you call if_config and it returns an error subsequent calls will immediately return 0 and won't repeat any initialization that failed.
This change keeps track of what's been initialized so that initialization can be resumed.
> allow retries of if_config

- Makefile
- gc/gccore.h
- gc/ogc/aes.h
- libogc/aes.c
@GaryOderNichts since it is mostly your code, feel free to review the changes in libogc to support the aes engine through /dev/aes
ill merge it when you accept the changes to your code
> aes: add code to encrypt/decrypt using the aes engine

- gc/ogc/gx.h
- libogc/gx.c
The function provides a wrapper to GX_SetTevIndirect to warp indirect textures more easily. The function is also undocumented at the moment.
> Add GX_SetTevIndWarp Function

- libaesnd/aesndlib.c
Current behavior when all voices are being used is to return the address of the last `AESNDPB` in `__aesndvoicepb[]`, which is being used already
> `AESND_AllocateVoiceWithArg`: Return `NULL` when all voices are being used

- Makefile
- gc/gccore.h
- gc/ogc/sha.h
- libogc/sha.c
while looking through the reverse engineering of the SHA engine for starstruck i noticed it was actually super easy to use, and applications like priiloader could use it to validate content integrity.
this would mean all software based sha implementations can be replaced with the hardware implementation on the wii.
this has been tested with the following code : 
```
//input should always be 64bit aligned, in the actual code this was not on the stack but rather a global
u8 input[0x0400000] [[gnu::aligned(64)]];
//actual test
gprintf("starting context\n");
sha_context context [[gnu::aligned(32)]];
u32 output[5] [[gnu::aligned(32)]];
memset(output, 0, sizeof(output));
ret = SHA_InitializeContext(&context);
if(ret < 0)
{
gprintf("failed to reset SHA : %d.\n", ret);
return 0;
}
memcpy(input, …
```
> sha: implement SHA engine calls

- gc/ogc/gu.h
- libogc/gu.c
Marking the immutable parameters as const can help the developer spot some errors.
I initially added `const` to the vector parameter of `c_guMtxRotAxisRad()`, but then the build failed because indeed the parameter is being modified by the function (which internally calls `c_guVecNormalize()` on it). This is a bit of a surprise, I'm tempted to modify the function implementation to create a copy of the vector, but first I wanted to check with you, to see if you agree. Another option is to add `const` and document that the vector must be normalized, but this would be a behavioural change which might break existing clients. Or we just leave it as it is :-)
> gu.h: add const in vector and matrix API

- libogc/dsp.c
pointed out by pokechu22, and does indeed seem wrong
> dsp: fix typo when yielding from certain messages (#130)

- libaesnd/aesndlib.c
- libaesnd/dspcode/dspmixer.s
courtesy to Extrems & @muff1n1634  for providing the fix
tested with 
[AESNDResetFix.zip](https://github.com/devkitPro/libogc/files/10960099/AESNDResetFix.zip)
> aesnd: fix AESND_Reset. free voices & fix cmpi of unsigned short.

- libogc/console.c
the x/y offsets were completely unused when doing a regular CON_Init, as it was just writing it to the framebuffer
> console: calculate in the x & y offset when writing to the framebuffer

- gc/ogc/card.h
- libogc/card.c
- libogc/dvd.c
- libogc/exi.c
- libogc/lwp_watchdog.c
- libogc/lwp_watchdog.inl
- libogc/si.c
- libogc/system.c
> system: correctly set/fetch time. split up system time from correct time

- Makefile
- gc/ogc/system.h
- libogc/sys_report.c
Adds SYS_Report to write messages to Dolphin's debug uart.
SYS_STDIO_Report redirects stderr (and optionally stdout) to the uart.
> add support for Dolphin debug messages

- libogc/dvd.c
This fixes a bug in `__dvd_statebusycb`, where if a DVD command block is cancelled, it incorrectly updates the state on the dummy command block instead of the executing one.
> Fixed setting cmdblk state incorrectly on cancels

- libasnd/dsp_mixer/dsp_mixer.s
I managed to fix the swapped stereo channels problem in the libasnd library. I found this problem accidentally while listened audio with hearphones plugged to the TV.
Fixes #169
> libasnd: Fixed the swapped stereo problem

- gc/ogc/gx.h
- libogc/gx.c
These values are written into the texture object by GX_InitTexObjLOD(), GX_InitTexObjMinLOD() and GX_InitTexObjMaxLOD() but there was no getter for them.
I tested the function like this:
```c
{   
GXTexObj tex;
GX_InitTexObj(&tex, NULL, 12, 23, GX_TF_RGB565, GX_REPEAT, GX_REPEAT, GX_TRUE);
GX_InitTexObjLOD(&tex, GX_LIN_MIP_LIN, GX_LIN_MIP_LIN, 2.5, 7.0, 0, GX_ENABLE, GX_ENABLE, GX_ANISO_1);  
f32 minlod, maxlod;                                                                            
GX_GetTexObjLOD(&tex, &minlod, &maxlod);                                                       
fprintf(stderr, "Minlod %f, maxlod %f\n", minlod, maxlod);                                     
}                                                                                                  
```
And …
> gx: add GX_GetTexObjLOD()

- libogc/gx.c
In the alpha input we should use only GX_CA_* registers.  Both GX_CC_A2 and GX_CA_ZERO evaluate to 7, so this is just a cosmetic issue.
The existing error is probably the result of a misunderstanding during reverse engineering.
> gx: use correct constant name for PASSCLR operation

- libogc/network_wii.c
poll() is generally more efficient and does not have a limitation on the number of file descriptors, but many libraries and programs out there still use select(), so let's make it easier to port them too.
This has been tested with the "chat" program from SDL_net ([this patch](https://github.com/devkitPro/pacman-packages/pull/374), but with the "`__wii__`" reimplementations using net_poll removed), and it seems to be working fine.
Note: I can add a net_poll() for the GameCube, if someone thinks it's worth it.
> network: implement net_select() for the Wii

- gc/network.h
- libogc/network_wii.c
Two commits, I suggest to not squash them.
Having this structure being 16 bytes long causes net_sendto not to work; setting it to 8 bytes means that we can get rid of a few magic numbers in libogc's code (which actually show that the structure is meant to be 8 bytes only).
Changes have been tested on both a real Wii and on Dolphin, using the sockettest and udptest from wii-examples.
> Network fixes

- gc/ogc/gx_struct.h
- gc/ogc/video_types.h
- libogc/video.c
The Wii arcade console (RVA-001) [only has a VGA connector](https://up.shiz.me/a/rva-001-mk8sf/P8230180.JPG), no composite. This PR adds support to libogc for video output over that connector. It has the following caveats:
- The RVA seems to be detected by the stock NAND boot programs by [checking for the existence of `/title/00000001/00000002/data/RVA.txt`](https://wiibrew.org/wiki/Wii#RVA) as opposed to some SC console type setting. As I was not quite sure how to factor this (there seems to be generally no console type detection in libogc), I left this out for now and the mode needs to be manually set using e.g.`VIDEO_Configure(&TVRgb480Prog)`, and it is not returned by `VIDEO_GetPreferredMode()` (yet).
- As the video encoder needs to be reconfigured when switching modes from and to …
> Video: add support for RGB/VGA output

- libogc/sys_report.c
> OSReport: fix sending message when its larger than the buffer #205

- libogc/gx.c
Please review it commit by commit, because the commit messages should help in understanding what is happening :-)
> Get rid of some more magic numbers

- libogc/gx.c
Oops! I've been mistakenly used the X value for the Y dimension as well. Hopefully this won't break many applications, both because this function is rarely used, both because often one uses the same value for both dimensions.
> gx: fix a copy&paste error recently introduced in GX_SetTevIndTile()

- libogc/console.c
Simplify color handling code and fix custom background color ( ESC[48;2;<r>;<g>;<b>m )
> Console fixes

- wiiuse/wpad.c
New Wiimote code has a silly bug I introduced when trying to clean stuff up which prevented Wiimotes which weren't already active from getting assigned active slots due to checking against the wrong active slot bounds.
> wiimote: Fix registered Wiimotes unable to get active slot

- libogc/exception.c
Exception handler now automatically returns to the HBC after timeout + Added a message that tells the user that they can press reset (or Z on their GameCube Controller) to skip timeout because users tended to just unplug their Wiis from power.
> Small bug fix.

- gc/ogc/console.h
- libogc/console.c
Adds precision to the expected values of various arguments/results of the console API
New internal helper functions for commonly repeated (tedious and prone to mistakes) pattern
More comments for non-intuitive/non-obvious implementation decisions that had to be done due to the mixing of "units"
NOT TESTED ON HARDWARE (or in any use), but logically sound (more than the previous mixed results, at least)
> console: fix writing out of bounds and writing unused memory

- libogc/wiisd.c
It does not read & write in the full SDHS speed (25MB/s) but does speed up SD card access. possible limitation @ ios
Tested with random benchmark tool : https://github.com/Unknowncmbk/Benchmark/blob/master/src/benchmark.cpp
improved write speed with +/- 1Mbps when writing 50MB files, and improved read speed by 0.1Mbps.
> sd: enable SDHS
